#!/bin/sh
set -eu

usage() {
    echo "usage: $0 BINARY CONFIG MUTATION" >&2
    exit 2
}

[ "$#" -eq 3 ] || usage
binary=$1
config=$2
mutation=$3
backend=${MBED_AGENT_LINUX_FIREWALL_BACKEND:-nftables}
test_root=/tmp/mbed-agent-linux-firewall-daemon-smoke
runtime_root=/tmp/mbed-agent
socket=$runtime_root/agent.sock

test -x "$binary"
test -f "$config"
test -f "$mutation"
command -v jq >/dev/null 2>&1
command -v od >/dev/null 2>&1
command -v awk >/dev/null 2>&1
command -v cmp >/dev/null 2>&1

case "$backend" in
    nftables)
        command -v nft >/dev/null 2>&1
        native_before=$test_root/nft.before
        native_after=$test_root/nft.after
        ;;
    iptables)
        for command in iptables ip6tables iptables-save ip6tables-save \
            iptables-restore ip6tables-restore; do
            command -v "$command" >/dev/null 2>&1
        done
        native_before=$test_root/iptables.before
        native_after=$test_root/iptables.after
        ;;
    *)
        echo "unsupported Linux firewall backend: $backend" >&2
        exit 1
        ;;
esac

[ ! -e "$test_root" ] || {
    echo "refusing an existing test root: $test_root" >&2
    exit 1
}
[ ! -e "$runtime_root" ] || {
    echo "refusing an existing runtime root: $runtime_root" >&2
    exit 1
}
mkdir -m 0700 "$test_root"

daemon_pid=
cleanup() {
    status=$?
    if [ -n "$daemon_pid" ]; then
        kill "$daemon_pid" 2>/dev/null || true
        wait "$daemon_pid" 2>/dev/null || true
    fi
    if [ "$status" -ne 0 ]; then
        tail -n 80 "$test_root/daemon.log" >&2 2>/dev/null || true
        tail -n 80 "$runtime_root/log/agent.log" >&2 2>/dev/null || true
        find "$runtime_root" -type f -name '*.nft' -exec sh -c \
            'echo "--- $1 ---" >&2; sed -n "1,220p" "$1" >&2' sh {} \; \
            2>/dev/null || true
    fi
    rm -rf "$test_root" "$runtime_root"
    exit "$status"
}
trap cleanup EXIT INT TERM

case "$backend" in
    nftables)
        nft list ruleset >"$native_before"
        ;;
    iptables)
        # Materialize builtin chains in an otherwise empty namespace so the
        # before/after snapshot is stable after the owned chain is removed.
        iptables -N MBED_AGENT_BOOTSTRAP
        iptables -X MBED_AGENT_BOOTSTRAP
        ip6tables -N MBED_AGENT_BOOTSTRAP
        ip6tables -X MBED_AGENT_BOOTSTRAP
        for table in mangle nat; do
            iptables -t "$table" -N MBED_AGENT_BOOTSTRAP
            iptables -t "$table" -X MBED_AGENT_BOOTSTRAP
            ip6tables -t "$table" -N MBED_AGENT_BOOTSTRAP
            ip6tables -t "$table" -X MBED_AGENT_BOOTSTRAP
        done
        iptables-save | sed '/^# Generated by/d;/^# Completed on/d' >"$native_before.v4"
        ip6tables-save | sed '/^# Generated by/d;/^# Completed on/d' >"$native_before.v6"
        ;;
esac

cp "$config" "$test_root/config.toml"
cp "$mutation" "$test_root/mutation.json"
chmod 0600 "$test_root/config.toml" "$test_root/mutation.json"
admin_password=$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n')
printf '%s\n' "$admin_password" | "$binary" auth hash-password >"$test_root/admin.hash"
admin_hash=$(tr -d '\r\n' <"$test_root/admin.hash")
awk -v hash="$admin_hash" '
    /^\[runtime\]$/ { section = "runtime" }
    /^\[auth\]$/ { section = "auth" }
    /^\[/ && $0 != "[runtime]" && $0 != "[auth]" { section = "" }
    section == "runtime" && /^rollback_confirm_timeout_secs[[:space:]]*=/ {
        print "rollback_confirm_timeout_secs = 5"; next
    }
    section == "auth" && /^enabled[[:space:]]*=/ {
        print "enabled = true"; next
    }
    section == "auth" && /^admin_password_hash[[:space:]]*=/ {
        print "admin_password_hash = \"" hash "\""; next
    }
    { print }
' "$test_root/config.toml" >"$test_root/config.next"
mv "$test_root/config.next" "$test_root/config.toml"
chmod 0600 "$test_root/config.toml"
rm -f "$test_root/admin.hash"

"$binary" daemon --config "$test_root/config.toml" >"$test_root/daemon.log" 2>&1 &
daemon_pid=$!
for _ in 1 2 3 4 5 6 7 8 9 10 11 12; do
    [ -S "$socket" ] && break
    kill -0 "$daemon_pid" 2>/dev/null || exit 1
    sleep 1
done
test -S "$socket"

printf '%s\n' "$admin_password" | "$binary" auth elevate --socket "$socket" >"$test_root/elevate.json"
jq -e '.ok == true' "$test_root/elevate.json" >/dev/null
unset admin_password

"$binary" change firewall-inventory --socket "$socket" >"$test_root/inventory.json"
jq -e '.ok == true' "$test_root/inventory.json" >/dev/null
"$binary" change firewall-plan --socket "$socket" <"$test_root/mutation.json" >"$test_root/plan.json"
jq -e '.ok == true' "$test_root/plan.json" >/dev/null
change_set_id=$(jq -r '.result.data.change_set_id' "$test_root/plan.json")
risk=$(jq -r '.result.data.plan.risk' "$test_root/plan.json")
test -n "$change_set_id" && test "$change_set_id" != null
[ "$risk" = r3 ]

"$binary" change approve "$change_set_id" --socket "$socket" >"$test_root/approval.json"
jq -e '.ok == true' "$test_root/approval.json" >/dev/null
approval_id=$(jq -r '.result.data.approval_id' "$test_root/approval.json")
if ! "$binary" change apply "$change_set_id" --approval-id "$approval_id" \
    --socket "$socket" <"$test_root/approval.json" >"$test_root/apply.json"; then
    cat "$test_root/apply.json" >&2 2>/dev/null || true
    "$binary" change get "$change_set_id" --socket "$socket" >"$test_root/failure-state.json" || true
    cat "$test_root/failure-state.json" >&2 2>/dev/null || true
    exit 1
fi
jq -e '.ok == true and .result.data.state == "awaiting_confirmation"' \
    "$test_root/apply.json" >/dev/null

case "$backend" in
    nftables)
        nft list table inet mbed_agent >"$test_root/managed.txt"
        ;;
    iptables)
        iptables-save >"$test_root/managed.v4"
        ip6tables-save >"$test_root/managed.v6"
        grep -F ':MBED_' "$test_root/managed.v4" >"$test_root/managed.txt" || {
            echo "iptables managed chains were not materialized" >&2
            cat "$test_root/managed.v4" >&2
            cat "$test_root/managed.v6" >&2
            exit 1
        }
        ;;
esac
echo "PASS: generic Linux $backend daemon transaction applied and awaits confirmation"

state=
for _ in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
    sleep 1
    "$binary" change get "$change_set_id" --socket "$socket" >"$test_root/state.json"
    state=$(jq -r '.result.data.state' "$test_root/state.json")
    [ "$state" = rolled_back ] && break
done
if [ "$state" != rolled_back ]; then
    echo "expected rollback, observed state: $state" >&2
    cat "$test_root/state.json" >&2
    find "$runtime_root/rollback" -maxdepth 2 -type f -print -exec sh -c \
        'echo "--- $1 ---" >&2; sed -n "1,240p" "$1" >&2' sh {} \\; \
        2>/dev/null || true
    exit 1
fi

case "$backend" in
    nftables)
        ! nft list table inet mbed_agent >/dev/null 2>&1
        nft list ruleset >"$native_after"
        cmp -s "$native_before" "$native_after"
        ;;
    iptables)
        iptables-save >"$test_root/rolled-back.v4"
        ip6tables-save >"$test_root/rolled-back.v6"
        ! grep -F ':MBED_' "$test_root/rolled-back.v4" >/dev/null
        iptables-save | sed '/^# Generated by/d;/^# Completed on/d' >"$native_after.v4"
        ip6tables-save | sed '/^# Generated by/d;/^# Completed on/d' >"$native_after.v6"
        if ! cmp -s "$native_before.v4" "$native_after.v4"; then
            echo "iptables v4 native snapshot mismatch after rollback" >&2
            diff -u "$native_before.v4" "$native_after.v4" >&2 || true
            exit 1
        fi
        if ! cmp -s "$native_before.v6" "$native_after.v6"; then
            echo "iptables v6 native snapshot mismatch after rollback" >&2
            diff -u "$native_before.v6" "$native_after.v6" >&2 || true
            exit 1
        fi
        ;;
esac
echo "PASS: generic Linux $backend daemon rollback restored the native snapshot"
